# Generated by Django 4.2.5 on 2023-10-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_orderdetail_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_sale",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_sale_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
